/**
 * testCases.ts
 * Preset test case library for FSOC Virtual Testbed.
 * Hidden disturbances are stored here and injected by the store,
 * never exposed to the D3 intelligence engine during analysis.
 */

import { TestCase } from '../types/intelligence';

export const PRESET_TEST_CASES: TestCase[] = [
  {
    id: 'tc_01',
    name: 'TC-01: Ground Turbulence',
    dashboard: 'D1',
    linkType: 'GROUND_GROUND',
    hiddenDisturbance: 'TURBULENCE',
    hiddenDisturbanceLabel: 'Atmospheric Turbulence',
    disturbanceIntensity: 0.65,
    durationS: 60,
    description: 'Moderate atmospheric turbulence is injected into the A→B ground link after 10s of normal operation. D3 must detect the anomaly and distinguish turbulence from fog/vibration.',
  },
  {
    id: 'tc_02',
    name: 'TC-02: Fog Attenuation',
    dashboard: 'D1',
    linkType: 'GROUND_GROUND',
    hiddenDisturbance: 'FOG',
    hiddenDisturbanceLabel: 'Fog / Atmospheric Attenuation',
    disturbanceIntensity: 0.70,
    durationS: 60,
    description: 'Dense fog gradually increases atmospheric attenuation. Key discriminator: steady SNR drop without beacon jitter (unlike turbulence).',
  },
  {
    id: 'tc_03',
    name: 'TC-03: Camera Vibration',
    dashboard: 'D1',
    linkType: 'GROUND_GROUND',
    hiddenDisturbance: 'CAMERA_VIBRATION',
    hiddenDisturbanceLabel: 'Camera Vibration',
    disturbanceIntensity: 0.75,
    durationS: 60,
    description: 'Terminal vibration causes periodic oscillating pointing error. Beacon itself is stable. D3 must identify the periodic camera-side signature vs atmospheric effects.',
  },
  {
    id: 'tc_04',
    name: 'TC-04: Beacon Loss',
    dashboard: 'D1',
    linkType: 'GROUND_GROUND',
    hiddenDisturbance: 'BEACON_LOSS',
    hiddenDisturbanceLabel: 'Beacon Loss / Occlusion',
    disturbanceIntensity: 1.0,
    durationS: 45,
    description: 'Beacon is suddenly occluded. Detection confidence drops to near zero, tracking is lost. Most severe scenario — immediate mitigation required.',
  },
  {
    id: 'tc_05',
    name: 'TC-05: Satellite Attitude Jitter',
    dashboard: 'D2',
    linkType: 'GROUND_SAT',
    hiddenDisturbance: 'ATTITUDE_JITTER',
    hiddenDisturbanceLabel: 'Spacecraft Attitude Jitter',
    disturbanceIntensity: 0.70,
    durationS: 60,
    description: 'Satellite attitude control disturbance causes periodic pointing oscillation in the space link. Ground atmospheric effects are absent. D3 must identify spacecraft-side cause.',
  },
  {
    id: 'tc_06',
    name: 'TC-06: Debris Interference',
    dashboard: 'D2',
    linkType: 'GROUND_SAT',
    hiddenDisturbance: 'DEBRIS_INTERFERENCE',
    hiddenDisturbanceLabel: 'Debris Path Interference',
    disturbanceIntensity: 0.80,
    durationS: 60,
    description: 'Space debris crosses the optical communication path, causing a momentary power and SNR drop. No jitter or pointing changes. D3 must correlate with debris proximity telemetry.',
  },
  {
    id: 'tc_07',
    name: 'TC-07: Sensor Noise',
    dashboard: 'D1',
    linkType: 'GROUND_GROUND',
    hiddenDisturbance: 'SENSOR_NOISE',
    hiddenDisturbanceLabel: 'Sensor / Detector Noise',
    disturbanceIntensity: 0.65,
    durationS: 60,
    description: 'Detector noise corrupts beacon coordinate measurements, reducing detection confidence without affecting optical power. Key discriminator: power/SNR remain stable.',
  },
  {
    id: 'tc_08',
    name: 'TC-08: Multi-Disturbance',
    dashboard: 'D1',
    linkType: 'GROUND_GROUND',
    hiddenDisturbance: 'MULTI_DISTURBANCE',
    hiddenDisturbanceLabel: 'Turbulence + Camera Vibration',
    disturbanceIntensity: 0.55,
    durationS: 75,
    description: 'Simultaneous turbulence and camera vibration create ambiguous mixed signatures. D3 should show multiple high-confidence hypotheses and acknowledge multi-cause uncertainty.',
  },
];
